### ISSUE TITLE
deploy MVP

### ISSUE THREAD

**Issue by louistrue** [IfcLCA/IfcLCA#31]
### Prerequisites
- A DigitalOcean account.
- A Droplet running Ubuntu or another preferred OS.
- Domain name (optional but recommended for production).
- Local SSH keys set up for secure access.

#### Creating a Droplet:
1. **Log in** to your DigitalOcean account.
2. Go to the **Droplets** section and click **Create Droplet**.
3. Choose an **image** (e.g., Ubuntu 20.04 LTS).
4. Select the **size** of the Droplet according to your application needs.
5. Choose the **datacenter region** closest to your users.
6. Add your **SSH keys** for secure access.
7. Click **Create Droplet**.

#### Accessing the Droplet:
```bash
ssh root@your_droplet_ip
```

#### Install Node.js:
```bash
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - # Install Node.js v14
sudo apt-get install -y nodejs
```

#### Install PM2:
```bash
npm install pm2@latest -g
```

#### Install MongoDB (if using MongoDB):
```bash
sudo apt update
sudo apt install -y mongodb
sudo systemctl start mongodb
sudo systemctl enable mongodb
```

#### Cloning Your Repository:
```bash
cd /var/www
git clone your_repository_url your_project_folder
cd your_project_folder
```

#### Install Dependencies:
```bash
npm install
```

#### Environment Configuration:
Create a `.env` file with your environment variables:
```bash
nano .env
```
Add configurations (e.g., DB connection, secret keys).

#### Start the Application with PM2:
```bash
pm2 start app.js --name "your_project_name"
```

#### Set up Nginx as a Reverse Proxy:
```bash
sudo apt install nginx
sudo nano /etc/nginx/sites-available/default
```

Replace the contents with the following:
```nginx
server {
    listen 80;
    server_name your_domain.com www.your_domain.com;

    location / {
        proxy_pass http://localhost:3000; # Port where Node.js app is running
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```
Enable the configuration and restart Nginx:
```bash
sudo nginx -t
sudo systemctl restart nginx
```

#### Setting up a Simple CI/CD with GitHub Actions:
Create a `.github/workflows/deploy.yml` file in your repository:
```yaml
name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Droplet
      run: |
        ssh -o StrictHostKeyChecking=no root@your_droplet_ip << 'EOF'
          cd /var/www/your_project_folder
          git pull
          npm install
          pm2 restart all
        EOF
```

### 5. Monitoring and Logs
- **Nginx Logs**:
  ```bash
  sudo tail -f /var/log/nginx/access.log
  sudo tail -f /var/log/nginx/error.log
  ```
- **Application Logs**:
  ```bash
  pm2 logs your_project_name
  ```

### 6. Security Enhancements
- Set up a firewall using `ufw`:
  ```bash
  sudo ufw enable
  sudo ufw allow 'Nginx Full'
  sudo ufw allow ssh
  ```
- Regularly update your server packages:
  ```bash
  sudo apt update && sudo apt upgrade
  ```

### 7. Database Backups and Maintenance
- Regularly back up your MongoDB or other databases.
- Use tools like `mongodump` for MongoDB backups.
